[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
junit_family = "xunit2"
minversion = "6.0"
norecursedirs = ["system_tests"]
testpaths = ["src", "tests"]
addopts = [
  "--import-mode=importlib",
]
